M48
; DRILL file {KiCad 9.0.3+dfsg-1} date 2026-05-10T16:43:49+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-10T16:43:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X32.355Y-51.61
X32.355Y-57.39
T2
X30.0Y-31.0
X30.0Y-78.0
X77.0Y-31.0
X77.0Y-78.0
M30
